#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
"console_title_template" = "{{.Folder}} in {{.PWD}}"
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    foreground = "#ff2b60"
    style = "plain"
    template = "󰄛 {{ .UserName }}@{{ .HostName }}"
    type = "session"

  [[blocks.segments]]
    foreground = "#4e2fc4"
    style = "plain"
    template = " on"
    type = "session"

  [[blocks.segments]]
    foreground = "#00ebff"
    style = "plain"
    template = " \uf07b {{ path .Path .Location }} "
    type = "path"
    [blocks.segments.properties]
      folder_separator_icon = "/"
      style = "full"

  [[blocks.segments]]
    foreground = "#14A5AE"
    powerline_symbol = "\ue0b0"
    style = "plain"
    template = "{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} "
    type = "git"
    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true

[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"
  
  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "#cbff00"
    template = " {{ .Full }} ({{ .Venv }}) "

  [[blocks.segments]]
    foreground = "#cd5e42"
    style = "plain"
    template = "\ue3bf "
    type = "root"

  [[blocks.segments]]
    foreground = "#ff8702"
    style = "plain"
    template = "# "
    type = "text"

